### ISSUE TITLE
Missing dummy-level instructions for getting started with Python 

### ISSUE THREAD

**Issue by mkvdhulst** [brightway-lca/brightway-interactive#14]
In the collected BW2 tutorials, all notebooks either completely skip on the very first first steps of installing python, creating environments and installing packages, or they explain it in a way that is not appropriate for a first-time coder. Often, the reader is referred to external sources, but these are often a bit too generic and their broadness can be overwhelming ("...but what do **I** need?"). To make the training also accessible to first-time coders, it would be desirable to include clear instructions that also connect to requirements in subsequent notebooks (i.e. instructions to connect to relevant channels, installing required packages etc.).

**Comment by mkvdhulst** [comment]
Relink images from imgbb to images folder in repo

**Comment by shirubana** [comment]
I would suggest using this page and giving some attribution to it -- https://pvlib-python.readthedocs.io/en/stable/user_guide/installation.html        the clear question and answer of what to do is very easy to follow, with enough information about the conda jupyter options.

**Comment by shirubana** [comment]
(let me know if you want to assign me this task of moddying it)

**Comment by michaelweinold** [comment]
The general Brightway setup is now covered [on the 'Setup' page of the documentation](https://documentation.brightway.dev/en/latest/source/setup/setup.html). The interactive documentation will not require setup.
