### ISSUE TITLE
Add licensing documentation to collected notebooks

### ISSUE THREAD

**Issue by KarinTreyer** [brightway-lca/brightway-interactive#15]
Notebooks from Brightway repos (https://github.com/brightway-lca/) can be used. If notebooks from other authors are included in this repo, the respective licenses need to be checked.

**Comment by KarinTreyer** [comment]
@BenPortner linked his introductory notebooks from https://github.com/BenPortner/brightway_recipes with this repo.

**Comment by michaelweinold** [comment]
https://github.com/brightway-lca/brightway-training/commit/34d2de34f77feecb542f7b8da1440a2fc298f043 added draft of curated list of Brightway training notebooks originally created by @KarinTreyer et al. during the [2022 Brightcon Hackathon on Documentation](https://2022.brightcon.link/).

**Comment by michaelweinold** [comment]
...compare: https://github.com/brightway-lca/notebook-collection
